### PR TITLE
New Processor: SelectEventsByMCDecayProcessor

### PR DESCRIPTION
**Pull request by ueinhaus**
BEGINRELEASENOTES
- New Processor: SelectEventsByMCDecayProcessor
    - Looks into MCParticles, selects events by decay mode(s) and, if the specified decay is found, sets Marlin::Processor::setReturnValue flag to 'true'.

ENDRELEASENOTES

### CODE REVIEW

**Comment by gaede** [comment]
This is a nice tool - but we have to find a different place for it as MarlinUtil cannot have actual processors (it is a utility library used by many packages that have processors).
Could you make a pull request in MarlinReco, e.g. in a new sub-package called Analysis/MCTruthTools.
Some minor comments on the implementation:
- maybe a name like `MCDecayChainSelector` would be more instructive
- isn't the restriction to two allowed decay chains a bit random ?
        - you could have exactly one and then the users can instantiate as many processors as they need decay chains
- using -1 as separator between (positive) numbers is a bit unusual
       - you could switch to stringvec, convert to unsigned  and then use any non numerical character as seperator, e.g. '|' or ';' ...
        - using stringvec you could even extend to *optionally* allow to specify the charge of the decays ( 11 - electron or positron, -11 positron, +11 electron)

**Comment by ueinhaus** [comment]
I suggested MarlinUtil because it is a generic event selection processor, which a priori has nothing to do with reconstruction. 
Also, in MarlinUtil there are processors, like SelectEvents.h and SkipNEvents.h, just not with the 'Processor' in their names - I can remove that part if you want. 
The SelectEventsByMCDecay(Processor) is in its basic functionality (select events by setReturnValue) very similar to the aforementioned ones, and I wanted to make this clear with the name and the place. 

I made 2 chains, because it is significantly more versatile than 1, in particular with the and/or option, but still concise and not overly complex. 

String seperators, negative pdg numbers and also (string) placeholders for groups of particles are certainly good suggestions for version 2 of the processor and I will be happy to implement them at a later point.

**Comment by gaede** [comment]
> I suggested MarlinUtil because it is a generic event selection processor, which a priori has nothing to do with reconstruction. Also, in MarlinUtil there are processors, like SelectEvents.h and SkipNEvents.h, just not with the 'Processor' in their names - I can remove that part if you want. The SelectEventsByMCDecay(Processor) is in its basic functionality (select events by setReturnValue) very similar to the aforementioned ones, and I wanted to make this clear with the name and the place. 

Yes, indeed there are old *legacy* processors in MarlinUtil that I had forgotten about. These should eventually also go (either to another package or for good). At the time we did not realize that linking against a package with marlin processors is not a good idea. If for example someone wants to update your processor in his local build it becomes a complete mess to steer with MARLIN_DLL, LD_LIBRARY_PATH and LD_PRELOAD which version of the processor is used...
So please choose a different, existing or new, package. There are many Analysis tools in MarlinReco, so I think this would be a good fit.

>I made 2 chains, because it is significantly more versatile than 1, in particular with the and/or option, but still concise and not overly complex.

Fine with me - just thought that having only one would be a bit more clear.

>String seperators, negative pdg numbers and also (string) placeholders for groups of particles are certainly good suggestions for version 2 of the processor and I will be happy to implement them at a later point. 

Also fine with me. Just need to keep in mind that if you change the format/layout of the steering files all of your users will have to adopt the new format.

**Comment by rete** [comment]
I close it. It will be moved to MarlinReco later on.

**Pull request closed without merging**
